CREATE DEFINER=`root`@`localhost` PROCEDURE `encrypt_db`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN 
DECLARE done INT DEFAULT 0; 
DECLARE TNAME CHAR(255); 

DECLARE table_names CURSOR for 
SELECT table_name FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND CREATE_OPTIONS NOT LIKE '%ENCRYPTION%'  AND TABLE_NAME<>'CODIGO' AND TABLE_NAME<>'LAYOUT_MEM' ORDER BY DATA_LENGTH;
 
DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1; 

OPEN table_names; 
SET FOREIGN_KEY_CHECKS=0;
WHILE done = 0 DO 

FETCH NEXT FROM table_names INTO TNAME; 

IF done = 0 THEN 
SET @SQL_TXT = CONCAT("ALTER TABLE ",TNAME," ENCRYPTION='Y'"); 
PREPARE stmt_name FROM @SQL_TXT; 
EXECUTE stmt_name; 
DEALLOCATE PREPARE stmt_name; 
END IF; 

END WHILE; 

CLOSE table_names; 

END