/*
 Generated by Claude Sonnet
*/
#ifndef MUNIT_H
#define MUNIT_H

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

// Add verbose mode flag
extern int munit_verbose_mode;

// Test case types
#define RUN 1
#define SUBMIT 2

#define MUNIT_FLOAT_EPSILON 0.000001

// Test function type
typedef void (*MunitTestFunc)(void);

// Test case structure
typedef struct {
    const char* name;
    MunitTestFunc test;
} MunitTest;

// Test suite structure
typedef struct {
    const char* name;
    MunitTest* tests;
} MunitSuite;

// Basic assert with verbose output
#define munit_assert(condition, message) do { \
    if (munit_verbose_mode) { \
        printf("Assert: %s - ", message); \
    } \
    if (!(condition)) { \
        printf("FAILED\nAssertion failed: %s\n", message); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED\n"); \
    } \
} while (0)

// Integer assertion with verbose output
#define munit_assert_int(actual, op, expected, message) do { \
    if (munit_verbose_mode) { \
        printf("Assert Int: %s - ", message); \
    } \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: %d %s %d\nActual: %d\n", \
            expected, #op, expected, actual); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%d %s %d)\n", actual, #op, expected); \
    } \
} while (0)

// String assertion with verbose output
#define munit_assert_string_equal(actual, expected, message) do { \
    if (munit_verbose_mode) { \
        printf("Assert String: %s - ", message); \
    } \
    if (strcmp((actual), (expected)) != 0) { \
        printf("FAILED\nExpected: \"%s\"\nActual: \"%s\"\n", \
            expected, actual); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (\"%s\" == \"%s\")\n", actual, expected); \
    } \
} while (0)

// Not null assertion with verbose output
#define munit_assert_not_null(ptr, message) do { \
    if (munit_verbose_mode) { \
        printf("Assert Not Null: %s - ", message); \
    } \
    if ((ptr) == NULL) { \
        printf("FAILED\nExpected: not NULL\nActual: NULL\n"); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (ptr = %p)\n", (void*)(ptr)); \
    } \
} while (0)

// String comparison
#define munit_assert_string_equal(actual, expected, message) do { \
    if (munit_verbose_mode) printf("Assert String: %s - ", message); \
    if (strcmp((actual), (expected)) != 0) { \
        printf("FAILED\nExpected: \"%s\"\nActual: \"%s\"\n", \
            expected, actual); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (\"%s\" == \"%s\")\n", actual, expected); \
    } \
} while (0)

// Integer assertions
#define munit_assert_int(actual, op, expected, message) do { \
    if (munit_verbose_mode) printf("Assert Int: %s - ", message); \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: %ld %s %d\nActual: %d\n", \
            actual, #op, expected, actual); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%d %s %d)\n", actual, #op, expected); \
    } \
} while (0)

// Float assertions
#define munit_assert_float_equal(actual, expected, message) do { \
    if (munit_verbose_mode) printf("Assert Float Equal: %s - ", message); \
    if (fabs((actual) - (expected)) > MUNIT_FLOAT_EPSILON) { \
        printf("FAILED\nExpected: %f to be approximately equal to %f\n" \
               "Actual: %f\nDifference: %f\n", \
               actual, expected, actual, fabs((actual) - (expected))); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%f ≈ %f)\n", actual, expected); \
    } \
} while (0)

#define munit_assert_float(actual, op, expected, message) do { \
    if (munit_verbose_mode) printf("Assert Float: %s - ", message); \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: %f %s %f\nActual: %f\n", \
            actual, #op, expected, actual); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%f %s %f)\n", actual, #op, expected); \
    } \
} while (0)

#define munit_assert_double_equal(actual, expected, message) do { \
    if (munit_verbose_mode) printf("Assert Double: %s - ", message); \
    if (fabs((actual) - (expected)) > 0.00001) { \
        printf("FAILED\nExpected: %f\nActual: %f\n", \
            (double)(expected), (double)(actual)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%f == %f)\n", (double)(actual), (double)(expected)); \
    } \
} while (0)

// Pointer assertions
#define munit_assert_ptr_not_equal(ptr1, ptr2, message) do { \
    if (munit_verbose_mode) printf("Assert Ptr Not Equal: %s - ", message); \
    if ((ptr1) == (ptr2)) { \
        printf("FAILED\nPointers are equal: %p\n", (void*)(ptr1)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%p != %p)\n", (void*)(ptr1), (void*)(ptr2)); \
    } \
} while (0)

#define munit_assert_ptr_equal(ptr1, ptr2, message) do { \
    if (munit_verbose_mode) printf("Assert Ptr Equal: %s - ", message); \
    if ((ptr1) != (ptr2)) { \
        printf("FAILED\nExpected: %p\nActual: %p\n", \
            (void*)(ptr2), (void*)(ptr1)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%p == %p)\n", (void*)(ptr1), (void*)(ptr2)); \
    } \
} while (0)

// Size comparison
#define munit_assert_size(actual, op, expected, message) do { \
    if (munit_verbose_mode) printf("Assert Size: %s - ", message); \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: %zu %s %zu\n", \
            (size_t)(expected), #op, (size_t)(actual)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (%zu %s %zu)\n", (size_t)(actual), #op, (size_t)(expected)); \
    } \
} while (0)

// Integer type assertions
#define munit_assert_uint8(actual, op, expected, message) do { \
    if (munit_verbose_mode) printf("Assert uint8: %s - ", message); \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: 0x%02X %s 0x%02X\n", \
            (uint8_t)(expected), #op, (uint8_t)(actual)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (0x%02X %s 0x%02X)\n", \
            (uint8_t)(actual), #op, (uint8_t)(expected)); \
    } \
} while (0)

#define munit_assert_uint16(actual, op, expected, message) do { \
    if (munit_verbose_mode) printf("Assert uint16: %s - ", message); \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: 0x%04X %s 0x%04X\n", \
            (uint16_t)(expected), #op, (uint16_t)(actual)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (0x%04X %s 0x%04X)\n", \
            (uint16_t)(actual), #op, (uint16_t)(expected)); \
    } \
} while (0)

#define munit_assert_uint32(actual, op, expected, message) do { \
    if (munit_verbose_mode) printf("Assert uint32: %s - ", message); \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: 0x%08X %s 0x%08X\n", \
            (uint32_t)(expected), #op, (uint32_t)(actual)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (0x%08X %s 0x%08X)\n", \
            (uint32_t)(actual), #op, (uint32_t)(expected)); \
    } \
} while (0)

#define munit_assert_uint64(actual, op, expected, message) do { \
    if (munit_verbose_mode) printf("Assert uint64: %s - ", message); \
    if (!((actual) op (expected))) { \
        printf("FAILED\nExpected: 0x%016lX %s 0x%016lX\n", \
            (uint64_t)(expected), #op, (uint64_t)(actual)); \
        exit(1); \
    } else if (munit_verbose_mode) { \
        printf("PASSED (0x%016lX %s 0x%016lX)\n", \
            (uint64_t)(actual), #op, (uint64_t)(expected)); \
    } \
} while (0)

// Test case macros
#define munit_case(type, name, ...) \
    void name(void) { \
        __VA_ARGS__ \
    }

// Test creation helper
#define munit_test(name, func) { name, func }
#define munit_null_test { NULL, NULL }

// Suite creation and runner functions
MunitSuite munit_suite(const char* name, MunitTest* tests);
MunitTest* munit_suite_get_tests(MunitSuite* suite);
int munit_suite_main(MunitSuite* suite, void* user_data, int argc, char* const* argv);

#endif // MUNIT_H
