#!/bin/bash
# Script to enable external access to Ollama API

echo "=== Enabling External Access for Ollama API ==="
echo ""
echo "Current status: Ollama is only listening on localhost (127.0.0.1:11434)"
echo "Your machine IP: 10.1.1.198"
echo ""
echo "To enable external access, run these commands:"
echo ""
echo "1. Stop Ollama service:"
echo "   sudo systemctl stop ollama"
echo ""
echo "2. Edit the service file:"
echo "   sudo systemctl edit --full ollama"
echo ""
echo "3. Find the [Service] section and add this line:"
echo '   Environment="OLLAMA_HOST=0.0.0.0"'
echo ""
echo "4. Save and exit, then reload and restart:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl restart ollama"
echo ""
echo "5. Verify it's listening on all interfaces:"
echo "   ss -tlnp | grep 11434"
echo ""
echo "6. Test from another machine:"
echo "   curl http://10.1.1.198:11434/api/version"
echo ""
echo "=== Security Note ==="
echo "Opening to 0.0.0.0 makes the API accessible from any network interface."
echo "Consider using firewall rules to restrict access:"
echo "   sudo ufw allow from 10.1.1.0/24 to any port 11434"
echo ""
echo "=== Alternative: Run Ollama with custom host ==="
echo "You can also run Ollama directly with a custom host:"
echo "   OLLAMA_HOST=0.0.0.0:11434 ollama serve"